### ISSUE TITLE
Do we want to remove the configuration options for harden_rand?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#179]
I fail to imagine a single use-case where someone would want to disabled the hardening of `rand` and its friends. I think that we should always enable it, and remove the possibility to disable it.

Rationale:

- People will deploy Snuffleupagus, disable all features, get pwned, and this will make bad advertisement for Snuffleupagus. Grsecurity had the same issue.
- The fact that `rand()` returns predictable sequences only dependent of the `srand` value isn't documented anywhere, people shouldn't rely on this. Things like `uniqid` and its friend are explicitely documented as not returning predictable stuff.
- This will simplify a bit the configuration
- This will prevent people from shooting themselves in the foot by disabling features "just in case it might break something"

I'm not too keen on giving the possibility to lower the security level (because lets be realist, people will just slap snuffleupagus on their machine with an empty configuration file) of a large part of the users, for the sake of reassuring a small number of them :/

**Comment by buixor** [comment]
While my heart definitely favors this option, letting the option available - from a _marketing_ point of view - we might avoid people not using sp "because there are some options that are force on you" or people coming up with unrealistic "what if ..."

**Comment by cfcs** [comment]
@buixor so you are going to lower the security of snuffleupagus (if there's a switch to turn something off, it's inevitable that someone will accidentally do) in order to cater for __people coming up with unrealistic "what if ..."__ ?
I'm pretty sure I could come up with unrealistic "what if ..." scenarios for all of snuffleupagus' features, including its existence ("what if the patch gets backdoored? one trust anchor is better than two") for example, so to me that doesn't seem like a valid concern.

As I see it, the only people who depend on `srand()/rand()` being reproducible (it is already highly platform- and version-dependent) are
1) attackers looking to fuck you up
2) security consultants looking to prove a point to you; that it is worth spending time on enabling this patch before 1) happens

**Comment by buixor** [comment]
@cfcs : it won't _lower_ the security of snuffleupagus, just letting the option of enabling / disabling it.
But I do agree with you, as I said, it's just only to avoid people not using it because we won't let them disable option X or Y and its possible side effects :)

**Comment by cfcs** [comment]
I think it *will lower the security of snuffleupagus* to have things that can be accidentally turned off, but of course that's my subjective view.

If this was a deterministic PRNG which could be used for unit testing systems or whatever I think there could be a point to being able to turn the patch off. But this is not the case with these functions; I honestly think there's no valid reason to turn it off, and the vanilla behaviour *does* result in a lot of security issues.

I'm positively certain that people will misunderstand the relevance of this; and if you'll bear with my anecdotal evidence: I had to demonstrate a bug in a password reset system recently and the developer responsible for the function said he *knew* that it wasn't *"military-grade random"*, but thought it would be sufficient for his PHP app when seeding with the current time in microseconds (which was then incidentally rounded off to seconds due to incorrect use of `microtime()`).
Developers make these mistakes all the time, and it's not because they're stupid - it's because this is a complicated domain to navigate, and they're good at writing web applications, not in assessing accumulated entropy levels in blackbox PRNG implementations and their application to security vulnerabilities.
It's just easier for everyone if `rand()` returns a random number, and if a reproducible, portable seeded PRNG can be used for the cases where you *do* want to control the seed.

**Comment by kkadosh** [comment]
Maybe it can be a good idea to enable it by default, and if someone really need to disable it, we can let him do with the `.disable()` ?

**Comment by kkadosh** [comment]
I think like @buixor , to let this option enable by default, and if someone really want to disable it, he has the `.disable()` option.

**Comment by cfcs** [comment]
@khadosh I agree that I don't think people will disable it by accident. I think what will realistically happen is that the person who packages it for an OS distribution will reason "oh, I don't want to break anyone's existing things, I'll just turn this off by default, and then people can enable it once they've verified that their software works with this feature turned on."
And then the latter part will never happen.

**Comment by crKontrol** [comment]
Hello everyone, 

As an exploitation point of view, we have two cases of behaviour here :

- The person who will install Snuffleupagus in order to _harden_ his PHP stack and not let funny stuff happend. So this person will prefer to have the _rand()_ function disable. 

- The person who want security but **not at the price to break his website** so this person need to have control over the configuration _(whether it is good from your point of view or not)_

By experience, imposing choice to the users once you have explained why you choose to do it (the "deal with it" arguments is not valid), it's fine and the users will probably understand your reasoning since you are the security experts.
I think that this function can be disabled "by design ". 

We want security and I agree too with @buixor and @kkadosh regarding the _marketing_ point of view and with good presentation/reason to the users, it will be fine. And if not you can still discuss with them their need with _rand()._

**BUT** this will not disclose the fact that this will need to be explained to the users you are dealing with why we choose to do that and the documentation MUST mention this ! Better than mention it, it will need to be in bold, underline etc... this will prevent for the users to tell you "oh I missed the mention" or "This is not documented" :)
