### ISSUE TITLE
Investigate a possible memory-leak

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#192]
A customer of ours reported a possible memory-leak when using snuffleupagus 0.2.2 on a LAMP stack:

Without it:
![without_sp](https://user-images.githubusercontent.com/325724/42623676-c383b07a-85c3-11e8-8c7e-772363d83b65.jpg)

With it:
![with_sp](https://user-images.githubusercontent.com/325724/42623677-c3a0f6e4-85c3-11e8-93e6-d48520e202e7.jpg)

It seems to also happen even with an empty snuffleupagus configuration file.

**Comment by xXx-caillou-xXx** [comment]
This seems to be fixed in `shoud_be_faster` branch.

With snuffleupagus on master:
![master](https://user-images.githubusercontent.com/27769215/42640663-1775a63c-85f3-11e8-87ca-e4a87f7806e5.png)

With snuffleupagus on should_be_faster:
![should_be_faster](https://user-images.githubusercontent.com/27769215/42640701-28e3f46e-85f3-11e8-81ab-1694804fbdca.png)

Without snuffleupagus:
![test](https://user-images.githubusercontent.com/27769215/42640727-3124fd76-85f3-11e8-8a89-2be3d03660c0.png)

**Comment by jvoisin** [comment]
Done in 7963580d72a358975133f86f01de2d2eab08ba38
